### ISSUE TITLE
View is resetting when navigating back to list

### ISSUE THREAD

**Issue by axcro7** [derqurps/noefinderlein#7] opened 2018-01-08 15:28 UTC
Every time I close an attraction to go back to the list the view is reset and I have to repeat all steps to search and scroll again. This is quite annoying when one is browsing several possible destinations for the next trip.

**Comment by derqurps** [comment] 2018-01-08 15:50
I can undestand your frustration, unfortunately this is by design. The upper back button is the quick-back button to the start of the app and the system back button on the lower end of the device should take you back to the list without loosing the scrolling.

This is made after some Android Design Guide suggestions, that the upper back button is different than the system back, but i do find that solution also a little bit annoying myself. Maybe i also misread the suggestion.

Perhaps you can make a suggestion what the upper back button should do instead of taking you to the "home screen".

**Comment by axcro7** [comment] 2018-01-08 16:00
Okay this is good to know! I didn't try the lower back button because of the risk to close the app completely (other apps have the toast message "tap again to close"...).
I'll check with other apps how they use the back button.

One problem might be, that the "home screen" is not evident to be one. It's more one list among others.

**Comment by derqurps** [comment] 2018-02-22 08:25
This should be finally resolved in 1.3.2 which is currently in beta.

The "up" navigation does now the same as the back button. And when no backstack is available it will display a toast before exiting.

Thanks for the help! :)

**Closed as completed by derqurps** 2018-02-22 08:25 UTC
